// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.hashcash.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  struct HcNetValue
//  {
//      Hash txSetHash;   // transaction set to apply to previous ledger
//      uint64 closeTime; // network close time
//  
//      // upgrades to apply to the previous ledger (usually empty)
//      // this is a vector of encoded 'LedgerUpgrade' so that nodes can drop
//      // unknown steps during consensus if needed.
//      // see notes below on 'LedgerUpgrade' for more detail
//      // max size is dictated by number of upgrade types (+ room for future)
//      UpgradeType upgrades<6>;
//  
//      // reserved for future use
//      union switch (int v)
//      {
//      case 0:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public class HcNetValue  {
  public HcNetValue () {}
  private Hash txSetHash;
  public Hash getTxSetHash() {
    return this.txSetHash;
  }
  public void setTxSetHash(Hash value) {
    this.txSetHash = value;
  }
  private Uint64 closeTime;
  public Uint64 getCloseTime() {
    return this.closeTime;
  }
  public void setCloseTime(Uint64 value) {
    this.closeTime = value;
  }
  private UpgradeType[] upgrades;
  public UpgradeType[] getUpgrades() {
    return this.upgrades;
  }
  public void setUpgrades(UpgradeType[] value) {
    this.upgrades = value;
  }
  private HcNetValueExt ext;
  public HcNetValueExt getExt() {
    return this.ext;
  }
  public void setExt(HcNetValueExt value) {
    this.ext = value;
  }
  public static void encode(XdrDataOutputStream stream, HcNetValue encodedHcNetValue) throws IOException{
    Hash.encode(stream, encodedHcNetValue.txSetHash);
    Uint64.encode(stream, encodedHcNetValue.closeTime);
    int upgradessize = encodedHcNetValue.getUpgrades().length;
    stream.writeInt(upgradessize);
    for (int i = 0; i < upgradessize; i++) {
      UpgradeType.encode(stream, encodedHcNetValue.upgrades[i]);
    }
    HcNetValueExt.encode(stream, encodedHcNetValue.ext);
  }
  public static HcNetValue decode(XdrDataInputStream stream) throws IOException {
    HcNetValue decodedHcNetValue = new HcNetValue();
    decodedHcNetValue.txSetHash = Hash.decode(stream);
    decodedHcNetValue.closeTime = Uint64.decode(stream);
    int upgradessize = stream.readInt();
    decodedHcNetValue.upgrades = new UpgradeType[upgradessize];
    for (int i = 0; i < upgradessize; i++) {
      decodedHcNetValue.upgrades[i] = UpgradeType.decode(stream);
    }
    decodedHcNetValue.ext = HcNetValueExt.decode(stream);
    return decodedHcNetValue;
  }

  public static class HcNetValueExt {
    public HcNetValueExt () {}
    Integer v;
    public Integer getDiscriminant() {
      return this.v;
    }
    public void setDiscriminant(Integer value) {
      this.v = value;
    }
    public static void encode(XdrDataOutputStream stream, HcNetValueExt encodedHcNetValueExt) throws IOException {
    stream.writeInt(encodedHcNetValueExt.getDiscriminant().intValue());
    switch (encodedHcNetValueExt.getDiscriminant()) {
    case 0:
    break;
    }
    }
    public static HcNetValueExt decode(XdrDataInputStream stream) throws IOException {
    HcNetValueExt decodedHcNetValueExt = new HcNetValueExt();
    Integer discriminant = stream.readInt();
    decodedHcNetValueExt.setDiscriminant(discriminant);
    switch (decodedHcNetValueExt.getDiscriminant()) {
    case 0:
    break;
    }
      return decodedHcNetValueExt;
    }

  }
}
